[tool.poetry]
name = "boxes-builds"
package-mode = false
version = "0.1.0"
description = "Record of boxes built with florianfesti's boxes"
authors = ["Seth Fischer <seth@fischer.nz>"]
license = "MIT"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.12"
# Note: boxes commit 27d444bf1f42a963933e8e87cdc366c196875831 breaks traylayout
boxes = {git = "https://github.com/florianfesti/boxes.git", rev = "68ef26a853df888760879da5f481c4be10dbdd6a"}
invoke = "^3.0.3"

[tool.poetry.group.dev.dependencies]
black = "^26.5.1"
isort = "^9.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
