[tool.poetry]
name = "boxes-builds"
version = "0.1.0"
description = "Record of boxes built with florianfesti's boxes"
authors = ["Seth Fischer <seth@fischer.nz>"]
license = "MIT"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.9"
boxes = {git = "https://github.com/florianfesti/boxes.git", rev = "5fc17de321f6a1491e0a9b1ce7535c3e73e9b062"}
invoke = "^2.0.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
