[tool.poetry]
name = "boxes-builds"
version = "0.1.0"
description = "Record of boxes built with florianfesti's boxes"
authors = ["Seth Fischer <seth@fischer.nz>"]
license = "MIT"
readme = "README.rst"
packages = [{include = "boxes_builds"}]

[tool.poetry.dependencies]
python = "^3.9"
qrcode = "7.3.1"  # https://github.com/florianfesti/boxes/pull/554
boxes = {git = "https://github.com/florianfesti/boxes.git", rev = "bf6e55bb364bbb9f12f5f242dae821b3b0271240"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
